### ISSUE TITLE
analysis data file size

### ISSUE THREAD

**Issue by HoldenJe** [WidebandPingFest/FishTetherExperiment#2]
@ross-alex: The compiled analysis file that includes all the wideband frequency response pings exceeds the maximum github file size (100mb).

## Potential fixes: 
**A**. Add to .gitignore file and provide instructions in README file for building this file in a local environment.
*This approach should generally be part of the project documentation regardless of this issue as it provides the road map for how the data was compiled. Generally however it is desirable to have the raw data available to be called directly from github in other analyses or the shiny app.*  
**B**. Apply filter to remove the rows where TS had a >6 dB compensation and only store this csv
*This seems like the most reasonable solution at present as the filter file is reduced to 65 MB (<100MB limit). As per approach **A** it is possible for users to build a copy of the unfiltered data for local use if required.*  
**C**. Save as Rdata files.
*Not a viable solution as the files size still exceeds the github files size limit. These files can be built and saved locally however to avoid having to recompile all the individual csv files for other exploratory data analysis.*  
**D**. Save as a compressed gz file  
*This option not tested given that **B** seems to be a viable solutions. It does appear possible that the gz file can be accessed and uncompressed in a R session by connecting to the raw github link as is done with a csv file.*  

## Code tasks  
[x] add code to save *.Rdata files
[x] update .gitignore file to exclude the oversized files

**Comment by HoldenJe** [comment]
@ross-alex  given that the custom functions and `read_tidy_EVFiles.R`  generates a complete data set as an output is there any value in still writing the allFishDat.csv files for each fish? They seem redundant at this point to me (except that my shiny app currently uses 2 of those files but the intent is to use new processed_AnalysisData.csv file).

**Comment by HoldenJe** [comment]
**E.** Even at 65MB github gives a warning that the file exceeds the recommended maximum size (50MB). Github message suggests using Git Large File Storage ([https://git-lfs.github.com](https://git-lfs.github.com)).  This might be a more viable option than others that have been considered.

**Comment by ross-alex** [comment]
Option **E** sounds like what we may need. Only drawback seems to be that everyone in the organization will need to download the LFS installed.

**Comment by HoldenJe** [comment]
Large file storage is desired route. Commit d0acdd0 was a merge on my local machine that integrated the file to LFS so there is no PR history on GH. The commit history is re-written in the process of doing the LFS `migrate`. In the process of refactoring the import code it was also determined that the individual *allFishDat.csv* files were no longer needed and were deleted (ef6f7b5).
